### ISSUE TITLE
Compatible methods with Arduino GSM/GPRS Shield library

### ISSUE THREAD

**Issue by lalarsson** [openwireless/3gim#1]
Hi!

Thanks for a really nice library for an awesome chip :)

I'd very much appreciate if you could provide an example of how library compatible with the aforementioned library.

As far as I can see the structure is same but since the classes doesn't implement any interfaces from Arduino I'm kind of having a hard time imagining how to use this library together with GSM.h...

Thank you very much in advance!

**Comment by openwireless** [comment]
Thank you for the message.
Please offer if you can help something.

@605e

**Comment by lalarsson** [comment]
@openwireless Thank you for replying without a proper answer.
